Fixes for Swift Package Manager
gabriel/yajl-objc pull request #50
Opened 2021-10-06 22:52 UTC by macinspak

Hi Gabriel,

Thanks for your patience while I tested out the changes thoroughly. It's working solidly now and apologies for missing a couple of things on the last pull request.

I've also updated the documentation to include instructions for SPM usage.

Please note, you will need to tag your release (I've nominated 0.3.4 in the README as that's your next revision number). If you don't do that, the instructions for SPM will most likely not work and you'll need to change the README to use a commit number or something in the SPM config.

Thanks again for such a useful library.

Andrew

2021-10-08 06:41 UTC, gabriel commented on README.md
> +You can use The Swift Package Manager to install SwiftyJSON by adding the proper description to your Package.swift file:
I'm confused about what this is about?

2021-10-08 06:43 UTC, gabriel requested changes

2021-10-08 06:43 UTC, gabriel commented on README.md
> +You can use The Swift Package Manager to install SwiftyJSON by adding the proper description to your Package.swift file:
Should this say yajl-objc?

2021-10-08 06:43 UTC, gabriel commented on README.md
> +    name: "YOUR_PROJECT_NAME",
Should name be yajl-objc?

2021-10-08 06:43 UTC, gabriel commented
Thanks for this!

2021-10-08 10:11 UTC, macinspak commented
Yes, that is just stupid isn’t it? I’ll fix it. Sorry again. Not great for confidence is it? 🙃

Sent from my iPhone

> On 8 Oct 2021, at 4:44 pm, Gabriel Handford ***@***.***> wrote:
> 
> ﻿
> Thanks for this!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-10-12 23:58 UTC, macinspak commented
Fixed

2021-10-13 21:57 UTC, merged